name: LearningSpigot # the plugins name as it should appear in the plugin list /pl
version: v0.9.1 # the plugin's version
author: David Holland
load: STARTUP
main: me.david.LearningSpigot.LearningSpigot
api-version: 1.19 # the version of the API you want to use, required starting with 1.13
commands:
  kit:
    description: adds a kit into the game
    usage: /kit
    permission: LearningSpigot.kit
  kick:
    description: kicks player
    usage: /kick
    permission: LearningSpigot.kick
  mute:
    description: mutes the server
    usage: /mute
    permission: LearningSpigot.mute
  fly:
    description: allows self to fly
    usage: /fly
    permission: LearningSpigot.fly
  invsee:
    description: View the inventory of another player.
    usage: /invsee
    permission: LearningSpigot.invsee
  ping:
    description: Shows your ping to the server. Add a player's name to view thier ping.
    usage: /ping
    permission: LearningSpigot.everyone
  game:
    description: Creates a game of Hide and seek
    usage: /game
    permission: LearningSpigot.everyone
  feed:
    description: feeds the player
    usage: /feed
    permission: LearningSpigot.feed
  heal:
    description: heals the player
    usage: /heal
    permission: LearningSpigot.heal
  #enchant:
   # description: add any enchant to any item
    #usage: /enchant
    # permission: LearningSpigot.admin
  fakeop:
    description: pretends to op a player
    usage: /fakeop
    permission: LearningSpigot.admin
  troll:
    description: trolls a player with custom sounds
    usage: /troll
    permission: LearningSpigot.admin
  pvpgame:
    description: Starts a game of PvP
    usage: /pvpgame
    permission: LearningSpigot.admin
  customitem:
    description: Grants custom items to a player
    usage: /customitem
    permission: LearningSpigot.*
  music:
    description: Plays music disks to players
    usage: /music
    permission: LearningSpigot.*;


